title: R8Q
author: CaptainIRS
description: Merhaba Bu Açıklama
google_analytics:
google_site_verification_content: 
disqus_forum_shortname: 

#Usernames and badges
htb_badge_no:
thm_badge_no:
show_thm_htb_badges_in_nav: false
<<<<<<< HEAD
github_username: 
hacker_news:
instagram: azrasekerci__

pinterest:
telegram: tekrarbaslat
=======
github_username: r8q
gitlab:
medium:
linkedin: Azra Sekerci
instagram:azrasekerci__
telegram: tekrarbaslat

>>>>>>> 36a5ac4 (Güncelleme yapıldı)

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true
